### ISSUE TITLE
Dark mode header images

### ISSUE THREAD

**Issue by grempe** [kwhitley/itty-durable#10]
The README header images for all of the itty * repos make it very hard to read the second word if Github is set to dark mode.

See:

https://share.getcloudapp.com/QwuALvOp

**Comment by kwhitley** [comment]
Ah yes, thanks for the reminder... had to fix this on itty-router as well.  Will roll this fix into `v1.x` releasing today!

**Comment by kwhitley** [comment]
Added to `v.1x` :)
