### ISSUE TITLE
Is state persistence automatic?

### ISSUE THREAD

**Issue by janat08** [kwhitley/itty-durable#12]
It seems like state is automatically persisted, and I didn't manage to use persistent storage. I just want to make sure, if it's so then this should be in readme.

**Comment by kwhitley** [comment]
Sorry for the late reply, but as this is just about to be re-released after an internal update, would love your input in this very poll:

https://github.com/kwhitley/itty-durable/discussions/16

**Comment by kwhitley** [comment]
By default auto-persistence will be off by default in `v1.x`.
