### ISSUE TITLE
alarm state

### ISSUE THREAD

**Issue by nikitapilgrim** [kwhitley/itty-durable#37]
If I get the state inside the alarm, it is not the current state, it is just the initialisation data

how can you get the current state and change it?

**Comment by kwhitley** [comment]
If you initialize the DO with { persist: true }, this should work without additional steps I believe.  I use this for the auto-expirations behind itty.sh :)

**Comment by kwhitley** [comment]
Otherwise, when the DO sleeps, memory/state is lost.

**Comment by nikitapilgrim** [comment]
I think you're right. Maybe either I was using an older version. (now upgraded to the latest version). Or maybe I did something wrong. Thanks
