### ISSUE TITLE
Question state

### ISSUE THREAD

**Issue by nikitapilgrim** [kwhitley/itty-durable#39]
I understand correctly that I can't use this.messages = []; For chat, right? Because as soon as the 128kb limit is reached, this.state.get('data') will be reset to initial?

**Comment by kwhitley** [comment]
> I understand correctly that I can't use this.messages = []; For chat, right? Because as soon as the 128kb limit is reached, this.state.get('data') will be reset to initial? 

That's correct... I need to create a mechanism to chunk up >128KB states and save/load them!  This has definitely been a limitation so far...
