### ISSUE TITLE
Add typescript types

### ISSUE THREAD

**Issue by nightvisi0n** [kwhitley/itty-durable#4]
Thanks for this awesome project. It would be great if you could add typescript types.

**Comment by mikecann** [comment]
Is this project dead? I just discovered it as I had done something simmilar (but significantly inferior) for my project: https://discord.com/channels/595317990191398933/773219443911819284/902760207212494889

**Comment by kwhitley** [comment]
Nope, not dead... just development was occurring in parallel to verify it was ready for production and harden the API.

`v1.x` is hopefully releasing today, perhaps with slightly incomplete docs, but the semi-final API.
