### ISSUE TITLE
Use `blockConcurrencyWhile` when constructor loads from storage 

### ISSUE THREAD

**Issue by mattfysh** [kwhitley/itty-durable#42]
According to the [docs](https://developers.cloudflare.com/durable-objects/learning/in-memory-state/) it's recommended to use `blockConcurrencyWhile`, e.g.

```ts
this.state.blockConcurrencyWhile(async () => {
  await this.loadFromStorage()
});
```

This ensures that while the object is being constructed, simultaneous requests don't come into the DO's methods - which may assume the memory has been hydrated from state storage

**Comment by lmaccherone** [comment]
I believe the example and guidance on that particular page of docs is superceded by the addition of input gates to the Durable Object system. See: https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/

You should still use it (or an [equivalent](https://medium.com/cloudflare-durable-objects-design-patterns/hydrating-from-external-sources-581ac6cf4cef)) for hydrating from an external source using `fetch()` but it is no longer necessary for fetching from DO storage.

**Comment by mattfysh** [comment]
Oh good to know, thanks! Seem like they should update the docs to remove the recommendation, or at least highlight a valid use case for using it.
