### ISSUE TITLE
make withDurables standalone 

### ISSUE THREAD

**Issue by fujohnwang** [kwhitley/itty-durable#50]
I think make withDurables an utility without dependency on router may be a good choice, Since people may use different router impl. from different frameworks.

Just an advice ;)

**Comment by kwhitley** [comment]
Great minds think alike!

In the upcoming version (@next currently), itty-durable:

- has no dependencies
- includes middleware (completely optional) for itty-router and hono
- adds auto persistence with a swappable store (you can read/write from anywhere, not just DO storage)

**Comment by kwhitley** [comment]
But specifically, the next version is framework agnostic... in the original version, the pairing of middleware+itty-durable (which used itty-router internally) was crucial to get the RPC mechanism to work.  Now, with native RPC finally being supported by Cloudflare, itty-durable gets to cut WAY back.  It shrinks to only ~400 bytes!
