### ISSUE TITLE
In Counter DO example `.clear()` should be `.reset()`

### ISSUE THREAD

**Issue by grempe** [kwhitley/itty-durable#7]
I believe this line in the example code in the README:

```js
// reset the durable)
.get('/reset', ({ Counter }) => Counter.get('test').clear())
```

should be:

```js
// reset the durable
.get('/reset', ({ Counter }) => Counter.get('test').reset())
```

Please also note the removal of the extraneous `)` at the end of the comment.

Having an example that shows setting the default state would also be helpful in relation to `.reset()`.

**Comment by kwhitley** [comment]
100% right, and fixed in the upcoming `v1.x` docs, thanks!!
