### ISSUE TITLE
Calling  a DO with a missing method returns incomplete error message

### ISSUE THREAD

**Issue by grempe** [kwhitley/itty-durable#8]
If I call a DO class with a method that has not yet been implemented on it I get a message like:

```json
{
    "error": "Durable Object I does not contain method foo()",
    "status": 500
}
```

Notice the name of the object printed is just `I` every time.

https://github.com/kwhitley/itty-durable/blob/v0.x/src/itty-durable.js#L63

**Comment by kwhitley** [comment]
Good catch - this is super old, but the problem appears to be with the minification.  By the time the error is thrown, the constructor name is already long lost.  Removing that in the upcoming version!
